server:
  port: 9296

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          url: https://github.com/nakul-chetiwal/microservice-circuitBreaker-docker-kubernetes/blob/main/application.yaml

